In [1]:
import IEA_model
import numpy as np
import torch
import pandas as pd
from torch.utils.data import DataLoader
import utility

from importlib import reload
reload(utility)
reload(IEA_model)

from sklearn.linear_model import LinearRegression

In [2]:
thold = 1e-2

In [3]:
df = pd.read_csv("gene_list_PCA/THOLD_{}.txt".format(thold))
idx_gene = df["index"].to_numpy()

idx_gene = np.load("../image_gene/ICA_no_correction/gene_idx_CV_major0.001.npy")


# data_train = utility.image_gene_dataset(train = True, cv = 0, n_cv = 5)
# data_validate = utility.image_gene_dataset(train = False, cv = 0, n_cv = 5)

train_loader = DataLoader(data_train, batch_size = 32)
validate_loader = DataLoader(data_validate, batch_size = 500)



/ocean/projects/asc170022p/juc91/anaconda/lib/python3.8/site-packages/pandas/core/frame.py:3065: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]
/ocean/projects/asc170022p/juc91/anaconda/lib/python3.8/site-packages/pandas/core/frame.py:3065: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]


In [6]:
M = IEA_model.IEA(train_loader, validate_loader, idx_gene = idx_gene, gamma = 1., beta = .1, alpha= 1., L = 2, n_patch = 32, n_rep = 5, lr = 1e-4).cuda()

In [7]:
len(idx_gene)

859

In [ ]:
M.train_model(150, 50,  2)

Step: 5
MSE: 0.9632537961006165
HSIC Loss: 0.00562392408028245
Loss: 1.9211852550506592


R2:-0.14404526129182338
opt R2:-1e+30


Step: 10
MSE: 1.4096885919570923
HSIC Loss: 0.010642731562256813
Loss: 2.8139424324035645


R2:-0.1144170555947213
opt R2:-1e+30


Step: 15
MSE: 0.8391925096511841
HSIC Loss: 0.0035936133936047554
Loss: 1.67225980758667


R2:-0.08795373377682153
opt R2:-1e+30


Step: 20
MSE: 1.149426817893982
HSIC Loss: 0.006139698904007673
Loss: 2.292776584625244


R2:-0.06440981723924281
opt R2:-1e+30


Step: 25
MSE: 1.1199135780334473
HSIC Loss: 0.0031372979283332825
Loss: 2.2366881370544434


R2:-0.054804719368144184
opt R2:-1e+30


Step: 30
MSE: 1.001353144645691
HSIC Loss: 0.004531318787485361
Loss: 1.9980093240737915


R2:-0.0431127479923032
opt R2:-1e+30


Step: 35
MSE: 1.0250155925750732
HSIC Loss: 0.004766121041029692
Loss: 2.0449748039245605


R2:-0.03605423884091582
opt R2:-1e+30


Step: 40
MSE: 1.0284473896026611
HSIC Loss: 0.005663638934493065
Loss: 2.057223320

In [103]:
M.train_model(2000, 1)

Step: 1505
gamma: 1.0
MSE: 0.9601121544837952
HSIC Loss: 0.021015869453549385
Loss: 0.9811280369758606


R2:0.038496361275813115
opt R2:0.03921623984185458


Step: 1510
gamma: 1.0
MSE: 0.9189276099205017
HSIC Loss: 0.03127510845661163
Loss: 0.9502027034759521


R2:0.035230834124370856
opt R2:0.03921623984185458


Step: 1515
gamma: 1.0
MSE: 1.0797860622406006
HSIC Loss: 0.026612404733896255
Loss: 1.1063984632492065


R2:0.039315299748819435
opt R2:0.03921623984185458


Step: 1520
gamma: 1.0
MSE: 0.8375232219696045
HSIC Loss: 0.030773339793086052
Loss: 0.8682965636253357


R2:0.03835004352598892
opt R2:0.039315299748819435


Step: 1525
gamma: 1.0
MSE: 0.9328092336654663
HSIC Loss: 0.06649946421384811
Loss: 0.999308705329895


R2:0.040161747579986064
opt R2:0.039315299748819435


Step: 1530
gamma: 1.0
MSE: 1.1145144701004028
HSIC Loss: 0.025730466470122337
Loss: 1.140244960784912


R2:0.03866308307900522
opt R2:0.040161747579986064


Step: 1535
gamma: 1.0
MSE: 0.8796724677085876
HSIC Loss

R2:0.04555726009082434
opt R2:0.046308967742539384


Step: 1770
gamma: 1.0
MSE: 1.1053389310836792
HSIC Loss: 0.028034456074237823
Loss: 1.1333733797073364


R2:0.0446895641418221
opt R2:0.046308967742539384


Step: 1775
gamma: 1.0
MSE: 0.8521745204925537
HSIC Loss: 0.025737904012203217
Loss: 0.8779124021530151


R2:0.035316406778082746
opt R2:0.046308967742539384


Step: 1780
gamma: 1.0
MSE: 0.8948687314987183
HSIC Loss: 0.03740463778376579
Loss: 0.9322733879089355


R2:0.04312603243820753
opt R2:0.046308967742539384


Step: 1785
gamma: 1.0
MSE: 0.8184541463851929
HSIC Loss: 0.039746347814798355
Loss: 0.8582004904747009


R2:0.03500335165578076
opt R2:0.046308967742539384


Step: 1790
gamma: 1.0
MSE: 0.8655775189399719
HSIC Loss: 0.03455342352390289
Loss: 0.9001309275627136


R2:0.04298951278125215
opt R2:0.046308967742539384


Step: 1795
gamma: 1.0
MSE: 0.9441798329353333
HSIC Loss: 0.030283123254776
Loss: 0.9744629859924316


R2:0.043531049793678785
opt R2:0.046308967742539384


Ste

In [116]:
M.train_model(2500, 1)

Step: 2005
gamma: 1.0
MSE: 0.9362448453903198
HSIC Loss: 0.033673226833343506
Loss: 0.9699180722236633


R2:0.046487668006646346
opt R2:0.04658217222904787


Step: 2010
gamma: 1.0
MSE: 0.8931191563606262
HSIC Loss: 0.04422362148761749
Loss: 0.9373427629470825


R2:0.043787713752014984
opt R2:0.04658217222904787


Step: 2015
gamma: 1.0
MSE: 1.043392539024353
HSIC Loss: 0.03404427319765091
Loss: 1.0774368047714233


R2:0.04630650183099978
opt R2:0.04658217222904787


Step: 2020
gamma: 1.0
MSE: 0.8135823607444763
HSIC Loss: 0.03505828604102135
Loss: 0.8486406207084656


R2:0.04586647473675334
opt R2:0.04658217222904787


Step: 2025
gamma: 1.0
MSE: 0.937045156955719
HSIC Loss: 0.07896755635738373
Loss: 1.0160126686096191


R2:0.0460096496599051
opt R2:0.04658217222904787


Step: 2030
gamma: 1.0
MSE: 1.1026138067245483
HSIC Loss: 0.03366647660732269
Loss: 1.1362802982330322


R2:0.045049234509859246
opt R2:0.04658217222904787


Step: 2035
gamma: 1.0
MSE: 0.840782880783081
HSIC Loss: 0.03611

R2:0.043683120771067806
opt R2:0.04658217222904787


Step: 2270
gamma: 1.0
MSE: 1.1097639799118042
HSIC Loss: 0.03231009468436241
Loss: 1.1420741081237793


R2:0.04337871827038614
opt R2:0.04658217222904787


Step: 2275
gamma: 1.0
MSE: 0.8472709655761719
HSIC Loss: 0.03167489543557167
Loss: 0.8789458870887756


R2:0.04146686949091779
opt R2:0.04658217222904787


Step: 2280
gamma: 1.0
MSE: 0.9182331562042236
HSIC Loss: 0.0449669174849987
Loss: 0.9632000923156738


R2:0.04164800865873356
opt R2:0.04658217222904787


Step: 2285
gamma: 1.0
MSE: 0.8056060671806335
HSIC Loss: 0.032420866191387177
Loss: 0.8380269408226013


R2:0.03678420961256579
opt R2:0.04658217222904787


Step: 2290
gamma: 1.0
MSE: 0.845119059085846
HSIC Loss: 0.02347628027200699
Loss: 0.8685953617095947


R2:0.041934123518171544
opt R2:0.04658217222904787


Step: 2295
gamma: 1.0
MSE: 0.9165194034576416
HSIC Loss: 0.029462723061442375
Loss: 0.9459820985794067


R2:0.04007446567782877
opt R2:0.04658217222904787


Step: 2300

In [8]:
sid_data, X_train, y_train = data_train[:]

In [10]:
X_npd = X_train[:16, :].cuda()

In [11]:
n_patch = 32

In [12]:
        n_sample = X_npd.shape[0]
        
        if n_patch is None:
            X_pd = X_npd.view(n_sample * 581, 128)
            n_patch = 581
            
        else:
            p_idx = np.random.choice( 581, size = n_patch * n_sample, replace = True)
            n_idx = np.array( [ [iii] * n_patch for iii in range(n_sample) ], int).flatten()
            X_pd = X_npd[n_idx, p_idx, :]


In [18]:
p_idx

array([559, 192, 359,   9, 277,  70, 472, 396, 314, 486, 551,  87, 174,
       537,  72, 115, 431, 448,  99, 177, 147, 423, 288, 265, 544, 543,
       244, 151, 510, 459, 183,  28, 128, 128,  53, 550, 488, 273, 335,
       388,  42, 442, 543, 257, 321,  57, 291, 119, 430,  82,  91, 398,
       565,  84, 203, 324,  47, 131, 180, 143, 227, 373, 560, 305, 169,
       448,  95, 197, 256, 292, 387, 554, 368, 201, 383, 512, 370, 555,
       383,  23, 130, 377,  98, 574, 123, 148, 209, 562, 411,  41,  58,
        36,  86,  43,  11, 307,  80,  32, 182, 128, 275, 174, 554, 371,
       184, 444, 488, 286, 280, 515,  94, 226, 269, 296, 328,  19, 410,
       450, 248, 180, 323, 260, 139, 461, 528, 152, 149, 110,  25, 464,
       117, 445, 228, 507, 121, 326, 469, 287, 525, 152,  41, 274, 552,
       438, 207, 166, 111, 349, 129, 216, 381,  24,  67, 234, 291, 555,
        32,  11, 212, 138, 421, 488, 539, 217, 307, 174, 148, 541, 579,
       547, 393,  73, 297, 394, 539, 429, 199, 423,  61, 341,  4

In [17]:
n_idx

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,
        2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,
        4,  4,  4,  4,  4,  4,  4,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,  5,
        5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  6,  7,  7

In [118]:
y_nm, mu_npl, log_var_npl, Z_nl = M(X_train.cuda())

In [119]:
Z = ( ( Z_nl - Z_nl.mean(0) ) / Z_nl.std(0) ).cpu().data.numpy()

In [120]:
MMM = LinearRegression()
MMM.fit(Z, y_train[:, idx_gene])

LinearRegression()

In [121]:
np.abs(MMM.coef_).sum(0)

array([138.60225 ,  15.817941,  19.01864 ,  13.900832,  19.468918],
      dtype=float32)

In [122]:
np.cov(Z.T)

array([[ 1.00000008e+00,  3.25824919e-02,  3.34948774e-02,
         3.56574857e-05,  6.97057414e-02],
       [ 3.25824919e-02,  1.00000009e+00,  7.34213530e-03,
        -1.38161183e-03,  4.66711523e-02],
       [ 3.34948774e-02,  7.34213530e-03,  9.99999976e-01,
         9.22000304e-04, -4.12752452e-02],
       [ 3.56574857e-05, -1.38161183e-03,  9.22000304e-04,
         1.00000004e+00,  9.01757131e-03],
       [ 6.97057414e-02,  4.66711523e-02, -4.12752452e-02,
         9.01757131e-03,  1.00000004e+00]])

In [81]:
M.n_patch